### ISSUE TITLE
Revisión del README

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-proyect_x#1]
He revisado el README:

- La propuesta de trabajo es ambigua. Debéis concretar a qué tipo de sensores y datos os referís. Tenéis que detallar mejor los objetivos.
- Eliminad los corchetes.
- En la lista de participantes usad el formato lista de Markdown.
- Podéis enlazar cada participante a su página web de GitHub.

**Comment by MarioTorre** [comment]
Ya creemos que hemos hecho todos los cambios, si nos lo puedes confirmar.
gracias.

**Comment by oscarperpinan** [comment]
Ok, adelante.
