### ISSUE TITLE
Menú del programa

### ISSUE THREAD

**Issue by lquintanac** [aigora/twIE_2021-proyect_x#2]
Debéis generar código que implemente un **menú provisional** con el que el usuario de vuestro programa debe interactuar. Este menú debe contener las opciones necesarias para acceder a las funcionalidades previstas, aunque aún no realizará ninguna acción. 
El menú estará implementado mediante un bucle `switch-case` y se repetirá indefinidamente hasta que el usuario decida salir del programa.

**Comment by orgynmobs** [comment]
Habéis subido los ficheros pero os falta cerrar la issue. Podéis hacerlo justo aquí abajo

**Comment by oscarperpinan** [comment]
El código debe estar en un fichero con extensión .c

**Comment by orgynmobs** [comment]
Cuando lo subáis cerrad la issue, y la milestone si está al 100%

**Comment by AlvaroVelascoMuela** [comment]
¿Cómo podemos hacer que la milestone llegue al 100%?

**Comment by oscarperpinan** [comment]
En primer lugar, tenéis que cerrar todas las issues asociadas a esa milestone. Cuando eso ocurra, id a la [lista de milestones](https://github.com/aigora/twIE_2021-proyect_x/milestones) y pulsad en "close".

**Comment by AlvaroVelascoMuela** [comment]
Genial, gracias.
