### ISSUE TITLE
Gestión de ficheros

### ISSUE THREAD

**Issue by lquintanac** [aigora/twIE_2021-proyect_x#4]
Debéis definir el **formato de los ficheros** que vuestro programa genera y lee (por ejemplo, el [formato CSV](https://es.wikipedia.org/wiki/Valores_separados_por_comas) es muy común para almacenar datos), y debéis **implementar el código** necesario para generar y leer estos ficheros.
Esta implementación puede tener cambios en la versión definitiva.

**Comment by AlvaroVelascoMuela** [comment]
Una pregunta, el objetivo de esta issue es crear los ficheros y el código para generarlos y leerlos ¿no? Es decir, creamos un nuevo file y redactamos como lo vamos a hacer y ponemos el código o solo ponemos el código.
